### ISSUE TITLE
Setting env with sensitive: true will still output the plain text of a secret

### ISSUE THREAD

**Issue by lucabrunox** [stategraph/stategraph#389]
### Describe the bug

Setting an env with sensitive: true must not show the plain text, as described in https://docs.terrateam.io/configuration-reference/workflows/#setting-environment-variables-using-the-source-method

As a side note it's not trimming the newline even though the docs say it should by default with trim_trailing_newlines.

### Steps to reproduce

In a workflow:

```
workflows:
  - tag_query: "..."
    plan:
      - type: oidc
        provider: gcp
        service_account: "..."
        workload_identity_provider: "..."
      - type: env
        name: CLOUDSDK_AUTH_ACCESS_TOKEN
        cmd: [ "python3", "-c", "import os; print(os.environ.get('GOOGLE_OAUTH_ACCESS_TOKEN'))" ]
        sensitive: true
      - type: init
      - type: plan
```

### Expected behavior

Do not show the plain text

### Actual behavior

It shows the plain text in the github workflow:

Step: env
Success: 👍

```
{
  "text": "<actual plain text secret here>\n",
  "method": "exec",
  "cmd": [
    "python3", "-c",
    "import os; print(os.environ.get('GOOGLE_OAUTH_ACCESS_TOKEN'))"
  ]
}
```

### Terrateam version & environment details

Using app.terrateam.io
