### ISSUE TITLE
Drift detection does not follow schedule / gets executed twice

### ISSUE THREAD

**Issue by michal-rybacki-soonly-pl** [stategraph/stategraph#445]
### Describe the bug

Drift detection is executed without coping with schedule provided inside of .terrateam/config.yml file in self hosted version of terrateam.

### Steps to reproduce

1. Setup terrateam application (self hosted) on particular repository with below config:
```
engine:
  name: tofu
  version: 1.9.0

workflows:
  - tag_query: ""
    environment: null
    lock_policy: "apply"
    plan:
      - type: run
        cmd: ['tofu', 'fmt', '-check']
      - type: init
      - type: run
        cmd: ['tofu', 'validate']
      - type: plan
    apply:
      - type: init
      - type: apply

hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: ${AWS_ROLE_ARN}
        region: ${AWS_REGION}
      - type: run
        cmd: ['ssh-keyscan-pre-hook', ${EXTERNAL_REPO}]
  plan:
    post:
      - type: drift_create_issue

drift:
  enabled: true
  schedules:
    default:
      tag_query: ""
      schedule: daily
      window:
        start: '21:00 GMT'
        end: '03:00 GMT'
```

2. Push configuration into master branch.
3. (optionally) Create a PR with any sort of changes, unrelated with .terrateam/config.yml file.

### Expected behavior

Drift detection should be executed within particular timeline provided in 
```
drift:
   schedules:
```
section.

### Actual behavior

Drift detection gets executed after creating PR or right after pushing configuration into master branch and then around the same time every day which does not fit into defined schedule. Another strange behaviour observed was the fact that it's being executed twice (one run after another). Not sure if that's related with the fact that terrateam server is scaled to two replicas.

### Terrateam version & environment details

Terrateam docker image version: `20250423-1036-60ace4d` with PostgreSQL 16.4 hosted on AWS RDS. 
2 server replicas hosted within Kubernetes cluster.

OpenTofu version: `1.9.0`

**Comment by michal-rybacki-soonly-pl** [comment]
Additionally, it looks like drift detection schedule changes are not really propagated into database and its drift_schedule table.

![Image](https://github.com/user-attachments/assets/71b76876-28bd-4921-9aef-a5ceea24b791)

**Comment by michal-rybacki-soonly-pl** [comment]
It turned out that schedule inside of 'schedules' section can not be named 'default', after changing that into something like that:

```
drift:
  enabled: true
  schedules:
    over_night_schedule:
      tag_query: ""
      schedule: daily
      window:
        start: '19:00 GMT'
        end: '20:00 GMT'
```

it worked: 

![Image](https://github.com/user-attachments/assets/10eb0e87-5b8a-466d-bed6-4632b677f866)

Please make sure to include that information in your docs reference for drift: https://docs.terrateam.io/configuration-reference/drift/ - thanks, issue can be closed!
