### ISSUE TITLE
Take into account modified Terragrunt dependencies when deciding which stacks to plan/apply

### ISSUE THREAD

**Issue by digorgonzola** [stategraph/stategraph#488]
### Describe the feature

When using Terragrunt in the way that is described in the [canonical example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/main/prod/us-east-1/prod/mysql/terragrunt.hcl), we often include "global" configuration such as the `root.hcl` file, or common environment settings from `_environment/dev.hcl` for example.

Managing these dependencies in the Terrateam configuration file can be somewhat ugly e.g.:
```yaml
dirs:
  # Ignore common tg/root.hcl file in base terragrunt folder
  tg:
    when_modified:
      file_patterns: []

  "tg/**/terragrunt.hcl":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl']

  # Capture Terragrunt dependencies
  "tg/**/alb/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'modules/aws_alb/**/*.tf', 'tg/_envcommon/alb.hcl']
  "tg/**/app/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'modules/aws_ecs/*.tf', 'tg/_envcommon/ecs.hcl']
  "tg/**/ecr/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'tg/_envcommon/ecr.hcl']
  "tg/**/github_oidc/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'tg/_envcommon/github_oidc.hcl']
  "tg/**/iam_roles/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'tg/_envcommon/iam_roles.hcl']
  "tg/**/mongodb/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'modules/mongodb/*.tf', 'tg/_envcommon/mongodb.hcl']
  "tg/**/squidproxy/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'tg/_envcommon/squidproxy.hcl']
  "tg/**/vpc/**":
    tags: [tg]
    when_modified:
      file_patterns: ['tg/root.hcl', '${DIR}/*.hcl', 'tg/_envcommon/vpc.hcl']

```

It would be really nice to have some sort of mechanism for taking into account the dependent configuration files and/or modules that are used by the Terragrunt stack to determine if a plan should be run.

For example, if I make a change to `modules/aws-alb/main/tf` then Terrateam needs to run a plan against `tg/mysuperapp/test/core/alb/terragrunt.hcl`.

### Why is this feature important?

1. Reduces Configuration Complexity
The current approach requires manually mapping every possible dependency relationship, which becomes unwieldy as infrastructure grows. A typical enterprise setup might have dozens of different service types, each requiring its own dependency mapping.

2. Prevents Missing Dependencies
Manual dependency management is error-prone. It's easy to forget to update Terrateam configuration when:
  - Adding new shared modules
  - Refactoring module paths
  - Adding new _envcommon configurations
  - Changing Terragrunt include blocks

3. Improves Maintainability

When dependencies are detected automatically:
  - There's no need to update Terrateam config when adding new modules
  - Refactoring module paths doesn't break CI/CD
  - New team members don't need to understand complex dependency mapping rules

### Additional context

Look into how Terramate CLI determines Terragrunt dependencies:
- https://terramate.io/docs/cli/change-detection/integrations/terragrunt
- https://github.com/terramate-io/terramate/blob/main/tg/tg_config_scanner.go
